name: build-pdf
on:
  push:
    branches:
    - main
    paths:
    - main.typ
    - figures/**
    - decorative_figures/**
    - .github/workflows/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Typst to PDF
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            main.typ
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v5
