name: compile
on:
  push:
    branches: 
    - main
    paths:
    - main.typ
    - figures/**
    - decorative_figures/**
    tags:
    - v*.*.*
    - prerelease-v*.*.*
  pull_request:
    branches:
    - main
    paths:
    - main.typ
    - figures/**
    - decorative_figures/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            main.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
