name: compile-test
on:
  pull_request:
    branches:
    - main
    paths:
    - main.typ
    - figures/**
    - decorative_figures/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            main.typ
